//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidade
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnexoPedidoAjuda
    {
        public int IdAnexoPedidoAjuda { get; set; }
        public int IdPedidoAjuda { get; set; }
        public int IdAnexo { get; set; }
        public bool Capa { get; set; }
    
        public virtual Anexo Anexo { get; set; }
        public virtual PedidoAjuda PedidoAjuda { get; set; }
    }
}
