//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidade
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatastrofeNatural
    {
        public int IdCatastrofeNatural { get; set; }
        public int IdMotivo { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
    
        public virtual Motivo Motivo { get; set; }
    }
}
