//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidade
{
    using System;
    using System.Collections.Generic;
    
    public partial class DadoBancario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DadoBancario()
        {
            this.UsuarioDadoBancario = new HashSet<UsuarioDadoBancario>();
            this.PedidoAjudaDadoBancario = new HashSet<PedidoAjudaDadoBancario>();
        }
    
        public int IdDadoBancario { get; set; }
        public string Nome { get; set; }
        public string Descricao { get; set; }
        public string Banco { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioDadoBancario> UsuarioDadoBancario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoAjudaDadoBancario> PedidoAjudaDadoBancario { get; set; }
    }
}
