//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidade
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CorrenteDoBemEntities : DbContext
    {
        public CorrenteDoBemEntities()
            : base("name=CorrenteDoBemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
       // public virtual DbSet<ANEXO> ANEXO { get; set; }
        public virtual DbSet<AnexoPedidoAjuda> AnexoPedidoAjuda { get; set; }
        public virtual DbSet<CatastrofeNatural> CatastrofeNatural { get; set; }
        public virtual DbSet<Contato> Contato { get; set; }
        public virtual DbSet<DadoBancario> DadoBancario { get; set; }
        public virtual DbSet<Doacao> Doacao { get; set; }
        public virtual DbSet<Endereco> Endereco { get; set; }
        public virtual DbSet<LocalEntrega> LocalEntrega { get; set; }
        public virtual DbSet<LocalEntregaEndereco> LocalEntregaEndereco { get; set; }
        public virtual DbSet<Motivo> Motivo { get; set; }
        public virtual DbSet<PedidoAjuda> PedidoAjuda { get; set; }
        public virtual DbSet<PedidoAjudaDoacao> PedidoAjudaDoacao { get; set; }
        public virtual DbSet<PedidoAjudaLocalEntrega> PedidoAjudaLocalEntrega { get; set; }
        public virtual DbSet<PrecisoAjuda> PrecisoAjuda { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
        public virtual DbSet<ProdutoDoacao> ProdutoDoacao { get; set; }
        public virtual DbSet<ProdutoPedidoAjuda> ProdutoPedidoAjuda { get; set; }
        public virtual DbSet<QueroAjudar> QueroAjudar { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioContato> UsuarioContato { get; set; }
        public virtual DbSet<UsuarioDadoBancario> UsuarioDadoBancario { get; set; }
        public virtual DbSet<PedidoAjudaDadoBancario> PedidoAjudaDadoBancario { get; set; }
    }
}
