//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidade
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoAjudaDadoBancario
    {
        public int IdPedidoAjudaDadoBancario { get; set; }
        public int IdPedidoAjuda { get; set; }
        public int IdDadoBancario { get; set; }
    
        public virtual DadoBancario DadoBancario { get; set; }
        public virtual PedidoAjuda PedidoAjuda { get; set; }
    }
}
