//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidade
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoAjuda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PedidoAjuda()
        {
            this.AnexoPedidoAjuda = new HashSet<AnexoPedidoAjuda>();
            this.PedidoAjudaDadoBancario = new HashSet<PedidoAjudaDadoBancario>();
            this.PedidoAjudaDoacao = new HashSet<PedidoAjudaDoacao>();
            this.PedidoAjudaLocalEntrega = new HashSet<PedidoAjudaLocalEntrega>();
            this.ProdutoPedidoAjuda = new HashSet<ProdutoPedidoAjuda>();
        }
    
        public int IdPedidoAjuda { get; set; }
        public int IdMotivo { get; set; }
        public Nullable<int> IdPrecisoAjuda { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DtAcontecimento { get; set; }
        public System.DateTime DtCadastro { get; set; }
        public int QuantidadeAfetados { get; set; }
        public string Titulo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnexoPedidoAjuda> AnexoPedidoAjuda { get; set; }
        public virtual Motivo Motivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoAjudaDadoBancario> PedidoAjudaDadoBancario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoAjudaDoacao> PedidoAjudaDoacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoAjudaLocalEntrega> PedidoAjudaLocalEntrega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProdutoPedidoAjuda> ProdutoPedidoAjuda { get; set; }
        public virtual PrecisoAjuda PrecisoAjuda { get; set; }
    }
}
