//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidade
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdutoDoacao
    {
        public int IdProdutoDoacao { get; set; }
        public int IdDoacao { get; set; }
        public int IdProduto { get; set; }
    
        public virtual Doacao Doacao { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
