//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidade
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioContato
    {
        public int IdUsuarioContato { get; set; }
        public int IdUsuario { get; set; }
        public int IdContato { get; set; }
    
        public virtual Contato Contato { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
