//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidade
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.PrecisoAjuda = new HashSet<PrecisoAjuda>();
            this.QueroAjudar = new HashSet<QueroAjudar>();
            this.UsuarioContato = new HashSet<UsuarioContato>();
            this.UsuarioDadoBancario = new HashSet<UsuarioDadoBancario>();
        }
    
        public int IdUsuario { get; set; }
        public Nullable<int> IdEndereco { get; set; }
        public string Nome { get; set; }
        public System.DateTime DtNascimento { get; set; }
        public string Login { get; set; }
        public string HashSenha { get; set; }
        public System.DateTime DtUltimoAcesso { get; set; }
    
        public virtual Endereco Endereco { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrecisoAjuda> PrecisoAjuda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QueroAjudar> QueroAjudar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioContato> UsuarioContato { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsuarioDadoBancario> UsuarioDadoBancario { get; set; }
    }
}
